### ISSUE TITLE
fixed columns and maxBodyHeight are not compatibale

### ISSUE THREAD

**Issue by pouryapb** [material-table-core/core#170]
I have a table without paging and I set max height for table so it fits to screen. but if I want to make some columns fixed, that component scrolls independent to the table rows! another thing, please consider people like me who are developing for a right to left language. least you can do is to add an id attribute to all components so I could at least be able to write my own css fixes. drag and drops are a mess as well (in rtl).
and PLEASE complete your documentation 😄
Thank you.

**Comment by matthewoestreich** [comment]
Absolutely, we try to consider all features. Please keep in mind this fork is meant to be a "community" fork - if you use it, and you need a feature, it would be extremely helpful if you could add that feature and send over a PR. That helps keep the wheels moving. Otherwise you'll be waiting on 2 people to finish all of these issues/PRs.

Same goes for documentation. It isn't my documentation. Its OUR documentation. If something is missing and you can add it, please do. What's the sense in opening an issue telling us things we already know?  Your time is better spent fixing the minor issues (major ones if you're feeling brave) and sending PRs vs opening an issue about..(idk)? Kind of feels like you just wanted to rant.

Lastly, per our guidelines, please provide a sandbox of the issue you are having.
