### ISSUE TITLE
Ability to Customize different types of edit fields (Boolean, Currency, etc...)

### ISSUE THREAD

**Issue by pouryapb** [material-table-core/core#185]
It's really useful to be able to change different edit fields in table, like for example I want to change date picker component because it only shows Gregorian date and I want to change that (localization doesn't do the trick before you say).
I might not know a good way but when I looked at the source code, doing something like this seems a little difficult right now.

**Comment by matthewoestreich** [comment]
Hello @pouryapb you can supply the type field under the columns prop. 

`columns={[{ title: "ID", field: "id", type: 'numeric' }]}`

The type can be one of 'boolean', 'numeric', 'date', 'datetime', 'time', 'currency'

**Comment by pouryapb** [comment]
@oze4 I think you didn't understand what I needed. type is not the problem. I want to change date picker when you edit a date field for example.

it would be DateField here:
![image](https://user-images.githubusercontent.com/34511048/116819997-0acc5f80-ab88-11eb-882e-b943fd661291.png)

**Comment by matthewoestreich** [comment]
I do not believe that is possible right as of right now. I believe you would need to override the MTableEditRow component in order to accomplish this.

**Comment by JGioia** [comment]
This is possible. The columns prop has a field "filterComponent" that allows you to override the filter component. The value of "filterComponent" must be a component that calls props.onFilterChanged(props.columnDef.tableData.id, event); on change. If you also you want to change how the filtering is done (ex. filter by year instead of the default day), you can supply 
 the "customFilterAndSearch" field to the columns prop with a function that takes in the filter value and a row and returns whether the row should be shown.
