### ISSUE TITLE
MaterialTable type does not have onQueryChange declared

### ISSUE THREAD

**Issue by ChinmayaNathany** [material-table-core/core#198]
Basically a clone of this issue - it'll be awesome if this can be solved :)
https://github.com/mbrn/material-table/issues/1965

**Comment by ChinmayaNathany** [comment]
Also, is there a recommended way to update 2 tables of the same type when an action is performed using TableRef?

Unable to figure out a direct way of doing so.

**Comment by ChinmayaNathany** [comment]
Will be awesome if someone can look into this - it seems like a relatively small fix :)
Thanks!

**Comment by matthewoestreich** [comment]
One of our goals is to be a community repo. We prefer to receive new PRs versus new issues *especially* for small, quick fixes (even more so if you use this project professionally).

With that being said, something like this should work but I want someone to confirm this due to my limited TS experience (I have experience with statically typed languages, so the paradigm is not foreign to me).

Does something like this work?

https://github.com/material-table-core/core/blob/1f183a9e5311928d3051f5205a5b2b2bee1893a4/types/index.d.ts#L88

@Domino987

**Comment by ChinmayaNathany** [comment]
@oze4 Thanks - will keep that in mind in the future!

It works for me and solves the issue - I definitely think this is better than the current implementation.

**Comment by Domino987** [comment]
@ChinmayaNathany hi,
Thanks for noticing this error.
if your version currently works, would you mind open a PR with these changes?

**Comment by matthewoestreich** [comment]
Fixed in v3.0.2
