### ISSUE TITLE
Add donation options

### ISSUE THREAD

**Issue by FalkF** [material-table-core/core#210]
I used material-table and material-table/core extensively in a project within the last year and am starting the conversation about open source contributions and support within the company I work for.
Could material-table/core profit from monetary support and how could this be done with it being a fork?
I cant promise anything but would like to use this project as an example for projects that deserve our gratitude.

**Comment by Domino987** [comment]
Hi,
great that you like it so far.
We already talked about this and we were thinking about adding an open collective account.
The money would be used so that we can take time out of our schedule to work on features.

I just added an open collective for us: https://opencollective.com/material-table-core

**Comment by matthewoestreich** [comment]
I agree with @Domino987!

**Comment by Domino987** [comment]
Closing since we now have options
