### ISSUE TITLE
Selection does not follow expected behaviour when using custom columns and onSelectionChange

### ISSUE THREAD

**Issue by pixelbadger** [material-table-core/core#246]
Demo here: https://codesandbox.io/s/nifty-star-b4zeg

**Describe the bug**
When a custom column is present, selection is enabled, and the onSelectionChange event callback contains a call to a useState setter, the selection state is not preserved.

**To Reproduce**

* Browse to demo
* Click the first checkbox
* Observe console debug log shows the correct row data, but the checkbox is not checked
* Click the second checkbox
* Observe console debug log does _not_ show two rows selected and the checkbox is not checked

**Expected behavior**
The checkbox to be checked, and for the state of selected items to be preserved between clicks.

**Desktop**

- OS: Windows 10
- Browser: Chrome
- Version: 91.0.4472.114

**Comment by matthewoestreich** [comment]
Nice catch. Thank you so much for this!

**Comment by matthewoestreich** [comment]
So, after quickly looking at this, it looks like this happens because the table is rerender due to setting state on row select. I do not remember this happening, though, so this could be a bug that was recently introduced.

I'll have to dig into this more tonight.. FYI - we have multiple misc issues open right now due to unnecessary rerenders - we are in the process of rewriting using React Context - see the `context` branch for more.

We are not the original authors, just trying to clean things up and continue to support the original project.

What are you wanting to accomplish? Maybe we can help you come up with a band-aid for now? This is kind of a big(ish) bug imo.

@Domino987 for visibility.

**Comment by pixelbadger** [comment]
As is always the way I found a workaround in the upstream repo's issues minutes after posting this bug. We're now stashing the selection state in a ref. Not a perfect solution because we're losing a state update we relied on for button enablement, but we can live with it.

**Comment by Domino987** [comment]
This is caused because we do not mutate the data objects anymore so without the tabledata, we have no way of tracking if the new data is actually new or the previous data. Especially because you are creating a new object on every render. And this makes it difficult to persist the state.

I was thinking of a way to get around it. The best way would be to give each row an id, which we could use to reference states between rerenders without mutating the props.

@oze4 What do you think about this?

**Comment by matthewoestreich** [comment]
@Domino987 I like the idea! It looks like rows are currently assigned an id, no? I thought each row had an id in tableData.id ? I could be wrong.

**Comment by Domino987** [comment]
This is just the index, so pretty much worthless unfortunately.

**Comment by Domino987** [comment]
This is actually caused by the function. Because you are creating a new function on every render, react thinks that you are passing new columns and the table state will be reseted. Please create a stable reference to columns or the function on columns. This will fix your code.

**Comment by matthewoestreich** [comment]
Oops didn't mean to reopen. Misclicked on mobile.
