### ISSUE TITLE
OnChangePage not working in production version

### ISSUE THREAD

**Issue by eslambasher** [material-table-core/core#247]
When i build reactjs app with webpack, the button 'next page' not working i get this error `Uncaught TypeError: e.onChangePage is not a function` but in local it's working good

![image](https://user-images.githubusercontent.com/15127303/124801400-19a00b80-df57-11eb-880a-7072323b17f3.png)

![image](https://user-images.githubusercontent.com/15127303/124801457-29b7eb00-df57-11eb-83cd-728b1430b537.png)

![image](https://user-images.githubusercontent.com/15127303/124801530-3a686100-df57-11eb-8686-9457ff6792f0.png)

**Comment by matthewoestreich** [comment]
Were you able to get this resolved? @eslambasher

**Comment by eslambasher** [comment]
@oze4 yeah it's was new version with material-ui 5 
![image](https://user-images.githubusercontent.com/15127303/124824764-1a469b00-df73-11eb-9b28-2c4bb47d2c8a.png)

link of breaking changes: https://material-table-core.com/docs/breaking-changes

**Comment by matthewoestreich** [comment]
Sweet - glad that helped!

**Comment by eslambasher** [comment]
@oze4 No in the end I was wrong and it was not the right solution, there is a real problem with the production version

**Comment by eslambasher** [comment]
the function onChangePage is still not found in the production version, I still do not know where it comes from

**Comment by Domino987** [comment]
@eslambasher  It seems like you are using muiV5 right? And which material-table version are you using?

**Comment by LuchoTurtle** [comment]
@Domino987 @eslambasher Isn't it rather the new latest stable version for MUI? They published a [v4.12.0](https://github.com/mui-org/material-ui/releases/tag/v4.12.0) version which deprecates a ton of stuff to transition to v5.

I'm personally using the latest stable MUI version (^4.11.4 which fetches 4.12.0 due to the caret) with the latest version of this repo and I get the same errors as well.

Perhaps we ought to change `material-table/core` 's PeerDependency of MUI from `"@material-ui/core": "^4.11.2",` to `"@material-ui/core": "~4.11.2",` to clear these errors temporarily. Or perhaps face these head-on and try to fix the deprecated errors according to this new MUI release 🤔

**Comment by LuchoTurtle** [comment]
An update on this:
I changed the dependency of my project of `@material-ui/core` to `~4.11.4` and my errors cleared away. So this is most likely an issue of MUI updating to the v4.12.1 and `material-table/core` being plagued with deprecation warnings due to this latest update from MUI.

**Comment by Domino987** [comment]
Ah so yes we did not incorporate the changes that were released two days ago.
Most of these changes are supported for the v5 branch with @next. 
Maybe we can get around to support v4.12.
But yes we should get the correct version in package json.

**Comment by eslambasher** [comment]
In reality the only thing I don't understand is how it's in local it works perfectly but once I build the app with webpack it doesn't work anymore

@LuchoTurtle i tryed with 4.11.2 but it still does not work

**Comment by LuchoTurtle** [comment]
Interesting. Assuming you're using the latest version of `material-table/core`, 4.11.2 *should* work. Even if you versioned it `~4.11.4`, it ought to work properly. Are you sure you're using the `onPageChange` props instead of `onChangePage`? I think the last one no longer exists 🤔

**Comment by eslambasher** [comment]
@LuchoTurtle i don't understand the last version of `material-table/core` it's v3.0.14 ? do u talking about `material-ui/core` ?

**Comment by LuchoTurtle** [comment]
@eslambasher Yeah, sorry if I was confusing 😅 . I meant that if you have something like this in your `package.json`
```
"@material-table/core": "^3.0.13",
"@material-ui/core": "~4.11.4"
```

it *should* work. You should use the `onPageChange` props instead of `onChangePage` you mentioned, since the latter doesn't seem to even exist in this latest version of `material-table/core`.

**Comment by Domino987** [comment]
So i just released a new version to use the new pagination props. I skipped one version but v3.0.16 is the one. This should work with mui v4.12.X

**Comment by eslambasher** [comment]
Great all working good thanks guys u r the best !
