### ISSUE TITLE
Drag animation removed

### ISSUE THREAD

**Issue by pedro-pool-by** [material-table-core/core#281]
Hello.

A few versions ago when you drag a column the column where is landing was like swaping, I mean there was an animation. Now there isn't. Is this a bug or is it a change expected?

https://codesandbox.io/s/material-table-starter-template-forked-kikgi?file=/src/index.js

![2021-07-28T20-53-27D0-09](https://user-images.githubusercontent.com/85236123/127394855-b9189042-d43e-4c34-828c-b56be37c0d43.gif)

**Comment by matthewoestreich** [comment]
Do we know which version was the last working version? That way I can check out the commits.

**Comment by matthewoestreich** [comment]
I've gone back to version 2.3.30 and this is still an issue. I wonder if the issue is with `react-beautiful-dnd`? @Domino987 thoughts?

**Comment by Domino987** [comment]
This is connected to `snapshot.isDragging ? provided.draggableProps.style : {}` to prevent a jump in styles most likely. But I do not get it to work to for both cases-

**Comment by matthewoestreich** [comment]
I'm not sure what you mean. Maybe we should create a branch and tag-team the issue?

**Comment by Domino987** [comment]
So previously, we always applied the provided style to all the headers. This lead to some jumping on start hover because some outer elements changed their offset. That's why we removed the style for all but the currently dragging header. But this, it seems, broke the reordering animation. I looked i to it but could not find a way to reconcile both of these problems yet.
