### ISSUE TITLE
Absolute Column

### ISSUE THREAD

**Issue by edgar-pozadas-by** [material-table-core/core#303]
Trying to add an absolute column

https://codesandbox.io/s/absolute-cols-uhdyn?file=/src/App.js

I added a column with position absolute but and it must be shown just when hover on row but when it shows all the columns get moved

any suggestion on how to manage this?

**Comment by matthewoestreich** [comment]
Which version are you on?

**Comment by edgar-pozadas-by** [comment]
Version 3.2.5

**Comment by flora8984461** [comment]
I checked v4.3, it happens still. I think it's the table did not have space for the hidden col and when hovers, it adjusts the col width. As a temp solution, I am not sure if this is acceptable, I make the col fixed width and instead of making display none, I make the text hidden. https://codesandbox.io/s/absolute-cols-forked-pso0b?file=/src/App.js 

I actually feel it's more of a display changing from none issue... ?

**Comment by matthewoestreich** [comment]
Sorry for the late response - let me dig into this.
