### ISSUE TITLE
Select all checkbox shows misleading icon

### ISSUE THREAD

**Issue by rjumatov** [material-table-core/core#350]
#### Description
When I select all checkboxes and deselect any row, the 'select all checkbox' shows a remove icon.
Clicking on that checkbox does not remove the selection but selects all unselected rows.
It would be assumed to remove the selection if the icon already indicates it.

#### Demo: [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-forked-12u8z?file=/src/index.js)
1. Click on select all checkbox
2. Deselect any row
3. Select all checkbox shows `IndeterminateCheckBox`
4. Click on select all again
5. Deselected rows get selected

#### Suggestions
If this feature cannot be implemented for some reason (e.g. if the total amount of rows and selected rows are not accessible) wouldn't it be possible to add the select all icon to the already existent `icons` prop?
This way I would not show the `IndeterminateCheckBox` to prevent showing the misleading icon.

**Comment by Domino987** [comment]
I think the default behavior for intermediate is to select all. Check here for reference: https://material.angular.io/components/checkbox/examples

I am not sure about the icon, since its not an icon but a checkbox. You would need to override all the functionality.

But you can create a PR and we will take a look on how you would achieve this.

**Comment by Domino987** [comment]
I am closing this since its the expected behavior
