### ISSUE TITLE
MaterialTable spacing is not behaving the same way as it was in version 4 of Material UI

### ISSUE THREAD

**Issue by georgewfsantos** [material-table-core/core#363]
![Screenshot_20211007_171930](https://user-images.githubusercontent.com/33661312/136457144-a7cc199c-15a1-49da-bd27-55ca090ce6dd.png)
![Screenshot_20211007_172732](https://user-images.githubusercontent.com/33661312/136457263-8d8a9691-c000-45d6-9c97-294c442ca959.png)
.

When we started migrating the application from Material UI v4 to v5,  the MaterialTable columns are misaligned and the spacing in the table is weird. We did not make any changes in our code, which is why it wouldn't help us to post any code here. But in the first screenshot above is how the table looked when using version 4 and the second one is how it looks now that we're using version 5 of Material UI. Thank you in advance for any information on this.

**Comment by Domino987** [comment]
The spacing in the demo looks fine.
Would you care to reproduce with v5 in a codesandbox?

**Comment by BrenoVelasco** [comment]
Hi @Domino987. I don't think the problem is, necessarily the spacing, but take a look at the different headers: v4 ones are white and have more "padding" it seems, and v5 is showing a grey background, looks thin and the text is a bit more left-aligned than it should be. Have any idea on what is causing that?
Thanks!

**Comment by Domino987** [comment]
Yes i noticed that, but as I mentioned, this should not be caused by the migration in itself, since I did not experience this in either the repo or in my code from work. Do you have a custom theme? Did you check inspect the element to see where the styles are coming from? If you can create s sandbox with this, i cold take a look.
