### ISSUE TITLE
Dynamically switching between tree data view and normal view is not working

### ISSUE THREAD

**Issue by pratik-nagpure** [material-table-core/core#388]
I want to dynamically decide to show tree data view or normal view
so, I am passing parentChildData property dynamically as below
` const parentChildData = (row: any, rows: any) =>rows.find((a: any) => a.id === row.parentId);`\

`<MaterialTable
..props,
parentChildData={showTreeView ? parentChildData : undefined}
/>`

I see that it is not working
Here is the sandbox link
  [CodeSandbox](https://codesandbox.io/s/gifted-violet-b2my4?file=/src/App.js:187-197)
  
  Steps to Reproduce -

- Go to the sandbox link
- Select/Unselect checkbox for "show tree view"
- See that it is not showing tree data view

**Comment by pratik-nagpure** [comment]
Hi @oze4 , any thoughts on this?

**Comment by matthewoestreich** [comment]
Sorry, just saw this - I've been missing for a little, I apologize. 

Let me take a look at this and I will get back to you.

**Comment by menehune23** [comment]
Any way to re-open this? It seems this ability is fundamentally broken.

We're running into this too, as we're trying to disable the tree view when any filter is applied. We do this because the tree behavior UX doesn't mix well with filtering (for instance, you'll see a result and it's ancestors when all we care about is the result itself).

Unfortunately, when the `parentChildData` is switched dynamically to `undefined` and back, there is some race condition or state retention that causes the results to not be filtered correctly (when `parentChildData` is first switched to `undefined`), and the hierarchy buttons to become nonfunctional (when the `parentChildData` is restored).
