### ISSUE TITLE
Render function is getting called twice

### ISSUE THREAD

**Issue by edgar-pozadas-by** [material-table-core/core#420]
I'm using the render function on columns object but I'm notice when something changes on the data, the render function is being call twice per row

on the screenshot below you will see the render function has been called twice:

![image](https://user-images.githubusercontent.com/80122564/143597781-fcbf0350-d15f-496a-8a06-2571308472b8.png)

this is the code sandbox where you can replicate the error

https://codesandbox.io/s/renderfunction-fx5h7

Open the console
Click on the button to change the data
Check function was called twice per row

I'm using version 4.3.10

**Comment by matthewoestreich** [comment]
It looks like sandbox is using an older version of `material-ui`. Per the error message, would you mind upgrading the version of `material-ui` (NOT `@material-table/core`) and trying again?

**Comment by matthewoestreich** [comment]
As far as each row rendering twice, I need to dig into why that is happening. @Domino987 any ideas? It appears something internally inside @material-table/core is forcing a second rerender per row. The actual component that uses the table only renders once, that's why I think something internally is causing the rerender for each row.

**Comment by edgar-arroyo-by** [comment]
I have been doing some research:
<img width="955" alt="image" src="https://user-images.githubusercontent.com/79274227/143658722-089ca4a5-b64c-489c-bf35-f1f6673b5d28.png">

In this little example, (which is the same @edgar-pozadas-by  provided but with one row) I got MuiTableCell called 6 times **(twice 3)** and the MuiTable row is called 2 times **(twice 1)**

I do not know if i explain myself :(

Then i go to the materia-table itself, and i saw that the componentDidUpdate was called **twice**. I added a small code snippet to check why it was called twice:

at src/material-table.js
```
  componentDidUpdate(prevProps, prevState) {
    console.log('componentUpdated on material-table component');
    Object.entries(this.props).forEach(
      ([key, val]) =>
        prevProps[key] !== val && console.log(`Prop '${key}' changed`)
    );
    if (this.state) {
      Object.entries(this.state).forEach(
        ([key, val]) =>
          prevState[key] !== val && console.log(`State '${key}' changed`)
      );
    }
```

**And i got this:**
<img width="452" alt="image" src="https://user-images.githubusercontent.com/79274227/143658879-8c1026df-8245-4bce-9f63-1b938a5becd6.png">


Using the well known Sherlock Holmes technique for debbuing I say: 
May be this related to that

- mt-core gets the data on the props
- mt-core do some process on that data
- mt-core saves that processed data into the state causing another rendering

If that is the case, the only thing that comes to my mind to fix this is, 
do this data-processed-procced in a memo, 
in which the props.data is a dependency,
so that memo will be called when the props.data gets updated and 
the result of the memo will be used as it is used the state nowadays


```
let proccessedData = useMemo(() => all the logic, [props.data])
```

not really sure if the root cause is what i say and not really sure if that is the solutions. Just wanna give a little help

**Comment by edgar-arroyo-by** [comment]
just a little visual help in order to describe what i think is the issue
<img width="453" alt="image" src="https://user-images.githubusercontent.com/79274227/143659472-6972df3d-fee7-4fbb-a5f4-b63fc5ce9e0e.png">

Right now, Not sure how to use memoization with react classes :( but we can always  learn :)

maybe with the help of should component update we can prevent the first render to happen :)

👯‍♂️ 

This projects rocks! and you rock @oze4  

i feel affection for this project 👯‍♂️

**Comment by Domino987** [comment]
Could this be caused by the react dev mode where every component is called twice?

**Comment by edgar-pozadas-by** [comment]
Sorry what do you mean with dev mode? running on local or react dev tools?

**Comment by Domino987** [comment]
Running on local with strict mode

**Comment by matthewoestreich** [comment]
@edgar-arroyo-by thank you for your research on this issue! There are def some kinks that need to be worked out as far as rerenders. However we handle it, it won't be a quick easy fix. 

Perhaps separating provided options with internal state could help?

**Comment by edgar-pozadas-by** [comment]
@oze4 is there any update on this issue?

**Comment by fernando-garza-by** [comment]
@oze4 Is there any ETA or plans to address this anytime soon? This one is impacting one of our customers and they are having poor performance on their table

**Comment by matthewoestreich** [comment]
I honestly haven't had a lot of time to dig deep into this but it's def in our radar. Let me take some time to look into the sandbox you provided and I'll try to come up with something. Apologies.

**Comment by Domino987** [comment]
I don't think this is something we can do since it'a react thing.
We render the table with empty data/useSate with not data.
One we get the data from the prop, we update them in an useEffect, setting the state.
This will always create a second render as can be seen tin this  [sandbox](https://codesandbox.io/s/billowing-darkness-yhrmq4?file=/src/App.js).
(Disclaimer, yes we use class components still for the main component, but the idea is the same).
Additional renders should also not be a problem, because they can happen for a million reasons.
Can you add a sandbox on why the render is super slow in oyur case? BEcause I never had a big problem with it, expcet if oyu have multiple inputs that update the whole table on change.
For specific usecases, it might be better to just render stuff yourself, depeding on your case.
But a sandbox would behelpfull.

Regarding the useMemo, it will only work for the data that i provided with a narray, not with the async data via an async function, that is passed ot the data prop.

And it is still a calss component, so useMemo is not available yet.
