### ISSUE TITLE
Sorting does not persist through rerenders [reproducible codesandbox]

### ISSUE THREAD

**Issue by ishake** [material-table-core/core#48]
Codesandbox: https://codesandbox.io/s/material-table-sorting-bug-mdzsx

**Description**
Our sorts are no longer persisting through rerenders for client-side data-driven tables (tables where an array is passed in for the data). (Note: if you switch to material-table v1.59.0 in the Codesandbox example, the bug disappears.)

**To Reproduce**
In sandbox, sort by one of the columns, then click one of "Set" buttons.

**Expected Behavior**
The sort persists after clicking the "Set" button.

**Actual Behavior**
The sort is reset to the initial sort after clicking the "Set" button.

**Environment**
OS: macOS
Browser: Chrome
Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by matthewoestreich** [comment]
Thanks for opening this! I'll review v1.59.0 to see what was changed. 

Is this happening in `@material-table/core` as well as `material-table`?  Just hoping to narrow down where the bug was introduced, and whether or not we inherited it.

**Comment by matthewoestreich** [comment]
@ishake it looks like this bug was introduced in 1.60.0 (obviously), somewhere around [this time](https://github.com/mbrn/material-table/commits/master?after=b7474ca0f5497f04ff3a3d50e709d86de7c639b0+279&branch=master) frame.

I believe [this](https://github.com/mbrn/material-table/commit/c90f0a76324a94701ff0aa12a98a89dade4ee424) commit may be the culprit.

@Domino987  thoughts?

**Comment by Domino987** [comment]
I will check this and storybook out tomorrow 👍

**Comment by matthewoestreich** [comment]
I just found the root of the issue - let me know if you want me to do anything further.  Thank you!

### This resolved the issue for me

Essentially, comment out L102-105 in the file below, then make L101 look like this: `const shouldReorder = isInit;`.

https://github.com/material-table-core/core/blob/2a78d36964c97ce98f995e0992e6ee31617d5e01/src/material-table.js#L101-L105

### For example

Change the above to...

```javascript
    const shouldReorder = isInit;
    // isInit ||
    // (defaultSortColumnIndex !== this.dataManager.orderBy &&
    //   !this.isRemoteData() &&
    //   defaultSortDirection !== this.dataManager.orderDirection);
```

... and it works as expected.

**Comment by koutto** [comment]
I posted the similar issue https://github.com/material-table-core/core/issues/51 
Is this workaround going to preserve the state of tree data (expanded/collapsed rows) ?

**Comment by matthewoestreich** [comment]
@koutto that is our goal. I don't really understand why this change was introduced, so I have been focusing elsewhere. 

@Domino987 was looking into this I believe.

**Comment by matthewoestreich** [comment]
All updates will be on https://github.com/material-table-core/core/issues/59.

Closing.

**Comment by aventide** [comment]
@oze4 I don't mean to re-open this issue, but I was hoping to get some clarification. Is the above workaround considered a full fix if it works ONLY when we take the `defaultSort` off?

I assume people will still want to be able to set a default sort without the problem of the state getting reset on data change.

**Comment by matthewoestreich** [comment]
Definitely not! 

So, I think our plans are to refactor into functional components while fixing issues. This repo has a lot of little bugs due to the fact it hasn't been updated in a while.

There are also better ways to handle things internally, such as using the context api vs the concept of a "data manager". 

After that we plan on refactoring JS into TS. 

That is why we are applying hotfixes like this. It's going to be rewritten within the next week anyhow (at least as far as the JS rewrite goes).

**Comment by matthewoestreich** [comment]
But if this hotfix caused a new issue, that issue still needs to be addressed imo.

**Comment by aventide** [comment]
@oze4 Sounds like you guys are seriously committed to making this library stable. Thanks so much!

**Comment by Google-cloud-datastore-b** [comment]
> [@koutto](https://github.com/koutto) that is our goal. I don't really understand why this change was introduced, so I have been focusing elsewhere.
> 
> [@Domino987](https://github.com/Domino987) was looking into this I believe.





https://backbone-events.github.io/flail665/
