### ISSUE TITLE
fix any types

### ISSUE THREAD

**Issue by tednaaa** [material-table-core/core#517]
Hi! sorry for deleted template :)

I contributed to the main repo and recently found out that there is a fork version, create a PR?

https://github.com/mbrn/material-table/pull/3116

**Comment by Domino987** [comment]
Hi, I am not sure what the original problem is. Can you create a sandbox with this? Since any should allow anything, it should just work. Or at least the error message. But only with a sandbox, we would be able to help you. The PR you added using T will also just result in using any, if no generic is provided because that is the fallback.

**Comment by tednaaa** [comment]
I rewrote all imports of `material-table` to `material-table-core`, and try to insert the same code, and there are no errors anymore, I didn’t understand why TS cursed at the incompatibility of any type, thanks! :)
