### ISSUE TITLE
CellStyle textAlign:"center" works headerStyle textAlign:"center" doesnt

### ISSUE THREAD

**Issue by Nulligma** [material-table-core/core#571]
https://postimg.cc/gxHnysXm

for columns data if you put textAlign of cellStyle to center it works but it does not work for headerStyle. How to center text in header? 

This problem does not occur in material-table.

**Comment by Domino987** [comment]
Could you add a sandbox for this?

**Comment by Piporono** [comment]
Hi @Domino987 

I also encounter the same problem (the textAlign attribute does not work for headerStyle, but it does work for cellStyle). You can quickly test it on any of the live demos in the "Style" category on this project website by adding `headerStyle: { textAlign: "center" }` to one of the column definition.

I also found out that the "draggable" div that wrap around the header cell might be the culprit, since if I disable draggable, I can center the text in the header again with the textAlign attribute.

**Comment by Nulligma** [comment]
> Could you add a sandbox for this?

https://codesandbox.io/s/material-table-starter-template-forked-5xbnm2?file=/src/index.js

**Comment by Nulligma** [comment]
> Hi @Domino987
> 
> I also encounter the same problem (the textAlign attribute does not work for headerStyle, but it does work for cellStyle). You can quickly test it on any of the live demos in the "Style" category on this project website by adding `headerStyle: { textAlign: "center" }` to one of the column definition.
> 
> I also found out that the "draggable" div that wrap around the header cell might be the culprit, since if I disable draggable, I can center the text in the header again with the textAlign attribute.

How to disable draggable?

**Comment by Domino987** [comment]
Yes this might be the cause but I do not see a way to resolve this, since the tableheader themselves cannot be draggable without breaking the table layout and it is needed to create the drag and drop functionality.

**Comment by GabrielMLV** [comment]
Add **draggable: false** works for me.
`options={{ 
draggable: false 
}}`

Version: "@material-table/core": "4.3.44"

**Comment by jhoanborges** [comment]
> Add **draggable: false** works for me. `options={{ draggable: false }}`
> 
> Version: "@material-table/core": "4.3.44"

this works, but i realize that header is not totally centered when sortable is true, because down arrow is hidden. Example:

<img width="244" height="171" alt="Image" src="https://github.com/user-attachments/assets/6a9e005e-1072-454c-850d-33f645c2bfbd" /> 

<img width="244" height="171" alt="Image" src="https://github.com/user-attachments/assets/cf7b771a-4fe6-4f85-bb33-963008fa1f62" />
