### ISSUE TITLE
Issue with expanding grouped item in tree data structure

### ISSUE THREAD

**Issue by inserty** [material-table-core/core#63]
When table display items in tree data mode and grouping is enable the table throws error:

![image](https://user-images.githubusercontent.com/28702252/104586765-345b8c80-5666-11eb-974e-46df0de90848.png)
![image](https://user-images.githubusercontent.com/28702252/104586775-36bde680-5666-11eb-9738-7f60e4989f84.png)

It is reproduceable in material-table doc example: https://material-table.com/#/docs/features/tree-data

**Comment by matthewoestreich** [comment]
Hey @inserty thanks for opening this!

Are you using `@material-table/core` or `material-table`? We are a fork of material-table (you can read more on this in the README of [this repo](https://github.com/material-table-core/core/blob/master/README.md)).

[This does not appear to be an issue with the latest version of `@material-table/core`](https://material-table-core.com/demos/tree-data/basic)

**Comment by inserty** [comment]
Hey @oze4,
I am using `@material-table/core` in `2.3.1` version.
I will update package to the newest version and let you know

**Comment by inserty** [comment]
Hi @oze4 ,
In the mean time I checked grouping in the example [https://material-table-core.com/demos/tree-data/basic/](url) but it is not working while you want to group by header.
![obraz](https://user-images.githubusercontent.com/28702252/104640046-62fa5700-56a8-11eb-97f6-6e220ef12039.png)

**Comment by matthewoestreich** [comment]
That looks like a separate issue. 

I must have misunderstood then. I thought the link you referenced was the issue (on material-table.com). I was under the impression it was a tree data issue not grouping. 

I'll get that fixed right quick.

**Comment by matthewoestreich** [comment]
I think I've discovered what the issue is just not where it's at. 

If you run that same code locally that's on the website, it gives you a more verbose error message. props.renderData.data is null in m-table-group-row.js but only when using grouping. If you use just tree data the prop is passed and isn't null.

**Comment by matthewoestreich** [comment]
I even reverted changes and the issue persists.

**Comment by matthewoestreich** [comment]
What is even more odd is that when I test local everything works. (see the `__tests__/demo` dir)..

But when I install the package, I get an error.


https://user-images.githubusercontent.com/21092343/104652840-531a4d00-567f-11eb-8077-3458a60002c1.mov

I have to run an errand but hopefully I can take a look at this later.

**Comment by matthewoestreich** [comment]
@cbaker this one is kind of annoying

**Comment by matthewoestreich** [comment]
@inserty I've gone back as far as `mbrn/material-table` `v1.20.0` but this issue persists (looks like it was inherited from a long time ago).

I understand the issue, but finding where it's at has turned out to be more difficult than anticipated.

**Comment by matthewoestreich** [comment]
https://github.com/mbrn/material-table/issues/1434

**Comment by aescobar95** [comment]
Hi everyone.
Exist any solution for this issue?

**Comment by Domino987** [comment]
So i dug a bit and it seems like the `parentChildData` prop and `grouping` do not like each other currently.

Can you guys show us your whole code? The code from the example currently breaks because it has both added. So treefiy and grouping are currently broken.

So share your code so we can fix this ;) @aescobar95 @inserty 

Seems like the best way is to prevent treefiying with `parentChildData` and grouping via moving columns into the header grouping area.
