### ISSUE TITLE
Default multisort is not working

### ISSUE THREAD

**Issue by ckchiu2** [material-table-core/core#648]
PR: #607

**Describe the bug**

Default value for multisorting is not applied.

**To Reproduce**

https://codesandbox.io/s/material-table-starter-template-forked-g7ozsw?file=/src/index.js

**Expected behavior**

Default value for multisorting should be applied

**Additional context**

1. For the test script for defaultOrderByCollection, the expect clause is called after the mouse click event, therefore the default value is not tested correctly
2. It breaks (my) datamanager.clearCriteria() because a replacement is not provided for the changeOrder() call, which is removed in the feature

**Comment by Domino987** [comment]
@Diiegoav would you mind looking into this?

**Comment by ewanmellor** [comment]
It works if you use the column index instead of the ID in `orderBy`:

```
   # Instead of this:
  defaultOrderByCollection: [
    {
      orderBy: "id",

  # Use this:
  defaultOrderByCollection: [
    {
      orderBy: 0,
```

Note that `index.d.ts` has this declaration:

```
export interface OrderByCollection {
  orderBy: number;
  orderDirection: string;
  sortOrder: number;
}
```

I think this is a mistake in the API though.  `orderBy` should use the column ID instead of the index, because that's exactly what the user is expecting, and it's less fragile to changes in the columns.  The way it is at the moment is exposing internal details of `data-manager` that don't belong in the API.
