### ISSUE TITLE
State & memo reset on Action override when re-render of material table triggered (codesandbox)

### ISSUE THREAD

**Issue by cbaker** [material-table-core/core#66]
I'm trying to override the Action component to return a custom selector that allows a user to utilize a preconfigured filter.
The state, memos, etc of my component get fully reset when the table data changes, not sure exactly what's going on here.

Minimal reproducible sandbox:
https://codesandbox.io/s/pedantic-rubin-ywvk6

**Comment by matthewoestreich** [comment]
Hello! Please see [here](https://github.com/material-table-core/core/issues/59) (I just renamed it, as it was poorly named). 

Also, [see here](https://github.com/material-table-core/core/pull/62) and I just published those changes to v2.3.6. Would you mind testing it out?

Please use #59 moving forward :) it all seems to be related to that.

**Comment by cbaker** [comment]
@oze4 I'm not sure that this is a state change more or less there lack of a state change. Are you personally familiar with how actions are rendered? It appears as if it is forcing a brand new instance every time without react's cache.

**Comment by matthewoestreich** [comment]
Right. So an unnecessary state change. Have you given v2.3.6 a shot? State is being reset to "default" correct? When you want the table to retain changes?

**Comment by matthewoestreich** [comment]
I'm on mobile right now but will be back within 30 min or so. I'll dig deeper then. There are also a handful of other issues I'm working on so idk when I can dig into this with my full attention.

**Comment by cbaker** [comment]
@oze4 Yea I suppose you're right, I was focusing more on the cause than the effect. 2.3.6 does not appear to solve this problem. Also if you've some relatively easy issues and want the work load taken off to get a look at this quicker let me know, I'm willing to pitch in.

**Comment by matthewoestreich** [comment]
That would be amazing! I reopened this issue. Sorry ab that.

**Comment by cbaker** [comment]
@oze4 tag me on some issue #'s

**Comment by cbaker** [comment]
Update this issue persists even when you don't override action and you override the icon button component via:
```
{
      icon: "link",
      tooltip: "blah",
      onClick: () => {},
      iconProps: {
          component: () => (
             <MyComponent
                 setData={setData}
                 sourceData={sourceData}
            />
        )
    }
}
```

**Comment by matthewoestreich** [comment]
Thank you for the update! I should be able to sit down and take a look at this in a couple of hours

**Comment by matthewoestreich** [comment]
@cbaker 

As far as the SandBox you provided, the table data is rerendered because you are completely changing the data being fed into material table. This is expected behavior, no? Change the data, expect the data to be rendered in the table, right? Or am I misunderstanding the issue?

```javascript
const Custom = ({ setData, origData, ...props }) => {
  const [times, setTimes] = useState(0);
  const p = useMemo(() => Math.random() * 100, []);

  const handleClick = () => {
    const newData = origData.filter((d) => d.b > 500);
    // ** COMMENTED OUT THIS LINE **
    // setData(newData);
    setTimes(times + 1);
  };

  return (
    <button onClick={handleClick}>
      {p} Click Me {times}
    </button>
  );
};
```

Commenting out the `setData` part fixes this...

[![Edit restless-framework-0pyri](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/restless-framework-0pyri?fontsize=14&hidenavigation=1&theme=dark)

**Comment by matthewoestreich** [comment]
Even when making a copy of `origData` (the data currently in the table) and setting that copy as the current data via `setData(...)` triggers this behavior **even though the data in the table looks the same, it isn't the same data since we made a copy of it**, therefore, the table is rerendered.

[![Edit dazzling-fermat-tmyc3](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-fermat-tmyc3?fontsize=14&hidenavigation=1&theme=dark)

I think down the line (we are currently refactoring) we need to look into how to solve this because we should be able to keep the header the same while only rerendering the table body.

**Comment by cbaker** [comment]
> @cbaker
> 
> As far as the SandBox you provided, the table data is rerendered because you are completely changing the data being fed into material table. This is expected behavior, no? Change the data, expect the data to be rendered in the table, right? Or am I misunderstanding the issue?
> 
> ```js
> const Custom = ({ setData, origData, ...props }) => {
>   const [times, setTimes] = useState(0);
>   const p = useMemo(() => Math.random() * 100, []);
> 
>   const handleClick = () => {
>     const newData = origData.filter((d) => d.b > 500);
>     // ** COMMENTED OUT THIS LINE **
>     // setData(newData);
>     setTimes(times + 1);
>   };
> 
>   return (
>     <button onClick={handleClick}>
>       {p} Click Me {times}
>     </button>
>   );
> };
> ```
> 
> Commenting out the `setData` part fixes this...
> 
> [![Edit restless-framework-0pyri](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/restless-framework-0pyri?fontsize=14&hidenavigation=1&theme=dark)

Correct me if I'm wrong but even when re-rendering child components should not lose their state. I would wager they are rendering table actions etc incorrectly.

**Comment by matthewoestreich** [comment]
It isn't losing it's state at all.  If a component has one of it's props change it will rerender. The `MaterialTable.data`prop is changing. You're essentially letting something from the "outside" change the state of something "inside". 

Meaning `<Custom />` is being passed the very func used to change internal state in `<MaterialTable />`.  

I understand Custom winds up being a child of MaterialTable, but you're allowing the child to change state of the parent, which kicks off a new render of that parent, which in turn rerenders a new child. 

That is why you only see this issue when the data prop is changed (`setData(...)`).

Due to a prop changing the entire component, `<MaterialTable />`, is "rendered" (it isn't even "re-rendering" it's completely rendering that data for the first time -- as far as JS is concerned it's a brand new object). Therefore, "rerendering" a new button in the header, along with everything else. 

Are there internal ways we could most likely prevent something like this from happening? Yes. Unfortunately, that will take some time (contributions welcome 😄 )

I think trying to understand your overall goal, and what you are actually trying to accomplish, would be valuable.

**Comment by matthewoestreich** [comment]
I even tried to memoize the entire MaterialTable component, but not even that works. Like I said, what you want to accomplish should be possible. ***But*** the fix will need to be internal to MaterialTable and how we handle data, etc.. internally.

[![Edit restless-framework-0pyri](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/restless-framework-0pyri?fontsize=14&hidenavigation=1&theme=dark)

**Comment by cbaker** [comment]
> It isn't losing it's state at all. If a component has one of it's props change it will rerender. The `MaterialTable.data`prop is changing. You're essentially letting something from the "outside" change the state of something "inside".
> 
> Meaning `<Custom />` is being passed the very func used to change internal state in `<MaterialTable />`.
> 
> I understand Custom winds up being a child of MaterialTable, but you're allowing the child to change state of the parent, which kicks off a new render of that parent, which in turn rerenders a new child.
> 
> That is why you only see this issue when the data prop is changed (`setData(...)`).
> 
> Due to a prop changing the entire component, `<MaterialTable />`, is "rendered" (it isn't even "re-rendering" it's completely rendering that data for the first time -- as far as JS is concerned it's a brand new object). Therefore, "rerendering" a new button in the header, along with everything else.
> 
> Are there internal ways we could most likely prevent something like this from happening? Yes. Unfortunately, that will take some time (contributions welcome 😄 )
> 
> I think trying to understand your overall goal, and what you are actually trying to accomplish, would be valuable.

We are trying to utilize the actions area for a preset filter dropdown. This obviously needs to change the data the table renders. I think there may be filters built into material-table by column, but we really wanted to implement ours this way, as it can filter on multiple fields & have a friendly label for our consumers.
![image](https://user-images.githubusercontent.com/16916670/104847324-5b57cf80-58ad-11eb-83c7-fbd0497794de.png)
![image](https://user-images.githubusercontent.com/16916670/104847330-60b51a00-58ad-11eb-9930-607b9426fd7f.png)

Also, the child component is indeed, losing its state when it's re-rendered.

**Comment by matthewoestreich** [comment]
Completely agree with you. We should be able to handle this internally. There should be a way to feed data into the table without triggering a rerender of the entire table, rather only the body. 

Open to ideas!

**Comment by cbaker** [comment]
Externally getting the ref then doing something along the line of the following example appears to remedy the problem?
```
const { current } = tableRef;
const newData = data.filter((d) => d.b < 10);
current.dataManager.setData(newData);
current.setState(current.dataManager.getRenderState());
```
https://codesandbox.io/s/pedantic-rubin-ywvk6
@oze4

I haven't had too much time to peek through the source code, I have made a fork and will look sometime later in the week though.

**Comment by matthewoestreich** [comment]
Looks good to me. @cbaker 

May want to make this a "util" or "helper" func? We have plans to do away with dataManager and introduce Context API.

**Comment by cbaker** [comment]
@oze4 the dataManager is a util that just formats data for the state, it doesn't actually hold state or attempt to, but yea the ctx api could be legit.

**Comment by matthewoestreich** [comment]
@cbaker I get that. But there are better, more obvious ways to write code.

If you [have a component](https://github.com/material-table-core/core/tree/master/src/components/MTableFilterRow) that needs [utils](https://github.com/material-table-core/core/blob/master/src/components/MTableFilterRow/utils.js), there are better ways to structure it. If it's something you can use globally, why not use a hook or context, etc..?

In my opinion, chucking ***all*** misc functions/helpers/formatters into a single file is a bad idea. But wait, there's more - it isn't just one global utils file, it's an entire folder. Things like this, in my opinion, make it extremely difficult to read through this code.

**Comment by cbaker** [comment]
@oze4 I'm not disagreeing with you at all, I was just stating what I saw in my quick peek this morning trying to find a workaround to get something working in production.

**Comment by sinclas** [comment]
I display a modal dialogue via changing the state of a flag.  
`onClick={()=>this.setState({displayFilterModal:true})}`
Without doing anything else, the state will rerender and I lose the group by column and sorting.  This wasn't expected.  I would have expected everything stays the same even if I change the remote data filters and apply the new results to the table.  The functionality is the user is able to change a date range and query.  They would expect the layout to remain but the number of records to change.  Eventually, we will support saving the layout and filters as a named layout setting in our app, I might be able to just reapply and own the state myself in the meantime.   

Side note:  Is there a donate button for the effort everyone is putting into this branch?  Would like to contribute.  ;)

**Comment by matthewoestreich** [comment]
Thank you @sinclas - this has been an issue for a while (referring to the table rerendering when it shouldn't).  We should prob give this higher priority as well, as it is kind of a big deal imo.

I will start troubleshooting this so that I can (hopefully) bring some solutions to the table which we can all review from there.

As far as donations are concerned, I don't feel comfortable accepting donations because I did not write 99% of the code in this repo. I am humbled by your suggestion, though, and thank you very much.  However, I think for now that money should be donated to mbrn (or @Domino987 - he has 2nd most LOC) for starting such an amazing project! We are just trying to support him by keeping it alive.

Personally, the thought matters more than the money (it really does mean a lot). Thank you.

**Comment by sinclas** [comment]
These projects, especially this one is large and can take a ton of time to get right.   
Wish I had some off-hours to pull and contribute ideas since I have a ton.  Thanks for the quick reply.   If you need someone to test a min/maj release, let me know and I can do a quick install and plug it into a sample project.  again.  thanks.

**Comment by fvicente** [comment]
In my case the problem was that I was using a funcional component and any change in the state reseted the sort defaults.
The solution was to apply useCallback in both `columns` definition and `options`.

Example:
```
  const columns = useCallback(() => {
    return [
        ...my columns...
    ]
  }, []);

  const options = useCallback(() => {
    return {
        ...my options...
    }
  }, []);

  return (
      <MaterialTable
        style={tableStyle}
        options={options()}
        columns={columns()}
        data={myDataState}
      />
  )
```

**Comment by Domino987** [comment]
@sinclas Does @fvicente workout work for you? Seems like changing options (a new object, even if the content is the same) might trigger this.

If we could narrow it down to this, it would make the fix easier to find.

We are also thinking of making the columns and data required to be the same instance since this would both make it easier for us to track changes (object reference changed => new rerender) and more predictable as well for our users. But we are still working on the correct way to go about that.

FYI, using the useMemo hook would make the code a bit easier to read:
```
const columns = useMemo(() => {
    return [
        ...my columns...
    ]
  }, []);

  const options = useMemo(() => {
    return {
        ...my options...
    }
  }, []);

  return (
      <MaterialTable
        style={tableStyle}
        options={options}
        columns={columns}
        data={myDataState}
      />
  )
```

On a personal note, yes we just added a sponsor button to help us spend more time on this project.

**Comment by sinclas** [comment]
Hi,

How would this work with the columns?   I tried a couple of ways to useMemo and wondering how to get this working.  I get React-specific errors on utilizing memo incorrectly.  

Thanks!
Steve

**Comment by Domino987** [comment]
I think this should be fixed. Is this still an issue?

**Comment by MarianBe** [comment]
Tying into this here, is there any way to keep the column-filter state when the `data` updates? I am able to keep the `Search`-State trough changing data, but the `Filter` gets reset every time my data updates

https://user-images.githubusercontent.com/773986/138057925-e86c6c72-ee99-4dc8-b568-8b325e0d7809.mov
