### ISSUE TITLE
Programmatically change current page

### ISSUE THREAD

**Issue by josueuitzil** [material-table-core/core#662]
Hi team, I have a question regarding the `page` prop of the table. If I pass this prop to the component and then update its value, then only the pagination will get updated. You can test it in the following sandbox: https://codesandbox.io/s/material-table-starter-template-forked-n8epbv?file=/src/index.js

From the name of the prop I initially thought that it could be used to programmatically change the current page of the table, however, I couldn't find documentation on this prop so I'm not sure if this is expected behavior or a bug. 

Is there any other way that the current page could be changed from outside the table? I think that passing a ref to the table and then using it to directly call the dataManager methods could work but seems a little hacky.

**Comment by Diiegoav** [comment]
@oze4 Reviewing to the code, seems like material-table/core, detects that if is passed `page and totalCount`, implementation will handle the paging in their side.

Could it be better to implement a new property to do this foreign paging? like `foreignPaging`, instead of relay on this two props `page, totalCount`.

**Comment by Diiegoav** [comment]
actually which could be the point of doing paging, when using local data ? currently if you do paging outside the material-table/core package, and do sort at same time, this got impacted do to the data refresh.
