### ISSUE TITLE
BulkUpdate didn't work - The "edit All" button still remain after entering the editing mode

### ISSUE THREAD

**Issue by ghyoo91** [material-table-core/core#696]
**Demo**
https://codesandbox.io/s/wizardly-scooby-g9qjgy?file=/src/App.js

**Describe the bug**
BulkUpdate didn't work - The "edit All" button still remain after entering the editing mode.
So, I couldn't confirm the changes or just get out of the editing mode.

**To Reproduce**
1. Make a simple table example with any data.
2. Add the onBulkUpdate function to editable props.
3. Click the "edit All" button to enter the bulk-editing mode.
4. Find some button for the discarding or saveing the changes.

**Expected behavior**
The "discard all changes" and "save all changes" button should be there if we enter the bulk-editing mode to confirm the changes(or not).

**Screenshots**
<img width="1025" alt="bulkUpdate" src="https://user-images.githubusercontent.com/20279300/206660324-ce2ec2ec-82ae-48de-8837-28ec0944bd6c.png">

**Desktop (please complete the following information):**
- OS: [e.g. iOS] : macOS Ventura v13.0.1
- Browser [e.g. chrome, safari] : Chrome(Version 108.0.5359.71)

**Comment by WhiteHat-Grey** [comment]
Hi, I am also experiencing the same issue after upgrading to material UI v5.  

**The issue:** 
- The edit all button does not change actions, meaning you cannot save or discard your changes on a bulk editable table.
- The only way to get the button to work is to click away from the tab that has the table open and then click back onto the table and the button will than change.

Expected behavior
The edit icon changes when clicked to a tuple 'save' or 'discard' changes icons and when the icons are clicked the edit icon is restored (After saving changes or discarding them).

**Comment by dalemarchand** [comment]
Same behavior can be seen on the material-table core website in the examples.

**Comment by ghyoo91** [comment]
I checked this behavior isn't reproduced any more in the v6.0.3 - I could use the bulkUpdate function to edit all data.
Thank you for fix this issue. I'll close the issue.
